name: Build Release AAB
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 python3-dev ffmpeg \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
          libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev \
          gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstrtspserver-1.0-dev \
          libx11-dev libxext-dev liblzma-dev libbz2-dev libunwind-dev \
          libsqlite3-dev tk-dev libgdbm-dev libc6-dev libffi-dev libssl-dev \
          autoconf automake libtool pkg-config
          
          pip3 install --user --upgrade buildozer "cython<3.0.0" virtualenv

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Buildozer (Release Mode)
        # Aquí usamos los Secrets que configuraste en Settings
        env:
          P_KEY_ALIAS: ${{ secrets.P_KEY_ALIAS }}
          P_KEYSTORE_PASSWORD: ${{ secrets.P_KEYSTORE_PASSWORD }}
          P_KEY_PASSWORD: ${{ secrets.P_KEY_PASSWORD }}
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Cambiamos 'debug' por 'release' para generar el .aab firmado
          buildozer -v android release

      - name: Upload AAB (Google Play Bundle)
        uses: actions/upload-artifact@v4
        with:
          name: AstroJump-Release-Bundle
          path: bin/*.apk
