name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Versión actualizada

      - name: Build with Buildozer
        # Corregido el nombre y versión del action
        uses: ArtemSerebrenninkov/buildozer-action@v1.2.1
        with:
          buildozer_version: master
          command: buildozer android debug

      - name: Upload APK
        # Versión v4 requerida por GitHub desde 2024
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk


