name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    # Forzamos Node 24 para evitar las advertencias de deprecación
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          # Corregido: libx11-dev en lugar de libx10-dev
          sudo apt install -y python3-pip build-essential git python3 python3-dev ffmpeg \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
          libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev \
          gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstrtspserver-1.0-dev \
          libx11-dev x11proto-xext-dev libxext-dev liblzma-dev libbz2-dev \
          libsqlite3-dev tk-dev libgdbm-dev libc6-dev libffi-dev libssl-dev \
          autoconf automake libtool pkg-config
          
          pip3 install --user --upgrade buildozer "cython<3.0.0" virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Este paso tardará unos 15-20 minutos
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AstroJump-Installer
          path: bin/*.apk





